// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gRPC-app.proto

package contract

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContractRequest struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Telnumber            string   `protobuf:"bytes,4,opt,name=telnumber,proto3" json:"telnumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractRequest) Reset()         { *m = ContractRequest{} }
func (m *ContractRequest) String() string { return proto.CompactTextString(m) }
func (*ContractRequest) ProtoMessage()    {}
func (*ContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0fd9afc461a34ba, []int{0}
}

func (m *ContractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractRequest.Unmarshal(m, b)
}
func (m *ContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractRequest.Marshal(b, m, deterministic)
}
func (m *ContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractRequest.Merge(m, src)
}
func (m *ContractRequest) XXX_Size() int {
	return xxx_messageInfo_ContractRequest.Size(m)
}
func (m *ContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContractRequest proto.InternalMessageInfo

func (m *ContractRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ContractRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *ContractRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *ContractRequest) GetTelnumber() string {
	if m != nil {
		return m.Telnumber
	}
	return ""
}

type ContractResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractResponse) Reset()         { *m = ContractResponse{} }
func (m *ContractResponse) String() string { return proto.CompactTextString(m) }
func (*ContractResponse) ProtoMessage()    {}
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0fd9afc461a34ba, []int{1}
}

func (m *ContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractResponse.Unmarshal(m, b)
}
func (m *ContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractResponse.Marshal(b, m, deterministic)
}
func (m *ContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractResponse.Merge(m, src)
}
func (m *ContractResponse) XXX_Size() int {
	return xxx_messageInfo_ContractResponse.Size(m)
}
func (m *ContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContractResponse proto.InternalMessageInfo

func (m *ContractResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractRequest)(nil), "contract.ContractRequest")
	proto.RegisterType((*ContractResponse)(nil), "contract.ContractResponse")
}

func init() { proto.RegisterFile("gRPC-app.proto", fileDescriptor_a0fd9afc461a34ba) }

var fileDescriptor_a0fd9afc461a34ba = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x0f, 0x0a, 0x70,
	0xd6, 0x4d, 0x2c, 0x28, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0x51, 0x6a, 0x65, 0xe4, 0xe2, 0x77, 0x86, 0x72, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0xe0, 0xf2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70,
	0x3e, 0x48, 0x2e, 0x27, 0xb1, 0xb8, 0x24, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x22, 0x07, 0xe3,
	0x0b, 0xc9, 0x70, 0x71, 0xa6, 0x65, 0x16, 0x41, 0x25, 0x99, 0xc1, 0x92, 0x08, 0x01, 0x90, 0x6c,
	0x49, 0x6a, 0x4e, 0x5e, 0x69, 0x6e, 0x52, 0x6a, 0x91, 0x04, 0x0b, 0x44, 0x16, 0x2e, 0xa0, 0xa4,
	0xc5, 0x25, 0x80, 0x70, 0x46, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51,
	0x6a, 0x71, 0x69, 0x0e, 0xcc, 0x15, 0x50, 0x9e, 0x51, 0x08, 0xc2, 0xc9, 0xc1, 0xa9, 0x45, 0x65,
	0x99, 0xc9, 0xa9, 0x42, 0x8e, 0x5c, 0x1c, 0x30, 0x21, 0x21, 0x49, 0x3d, 0x98, 0x6b, 0xf5, 0xd0,
	0x7c, 0x26, 0x25, 0x85, 0x4d, 0x0a, 0x62, 0x5b, 0x12, 0x1b, 0x38, 0x68, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc9, 0xa8, 0x2d, 0x34, 0x2c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContractServiceClient is the client API for ContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContractServiceClient interface {
	Contract(ctx context.Context, in *ContractRequest, opts ...grpc.CallOption) (*ContractResponse, error)
}

type contractServiceClient struct {
	cc *grpc.ClientConn
}

func NewContractServiceClient(cc *grpc.ClientConn) ContractServiceClient {
	return &contractServiceClient{cc}
}

func (c *contractServiceClient) Contract(ctx context.Context, in *ContractRequest, opts ...grpc.CallOption) (*ContractResponse, error) {
	out := new(ContractResponse)
	err := c.cc.Invoke(ctx, "/contract.ContractService/Contract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServiceServer is the server API for ContractService service.
type ContractServiceServer interface {
	Contract(context.Context, *ContractRequest) (*ContractResponse, error)
}

// UnimplementedContractServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContractServiceServer struct {
}

func (*UnimplementedContractServiceServer) Contract(ctx context.Context, req *ContractRequest) (*ContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Contract not implemented")
}

func RegisterContractServiceServer(s *grpc.Server, srv ContractServiceServer) {
	s.RegisterService(&_ContractService_serviceDesc, srv)
}

func _ContractService_Contract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).Contract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.ContractService/Contract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).Contract(ctx, req.(*ContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContractService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contract.ContractService",
	HandlerType: (*ContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Contract",
			Handler:    _ContractService_Contract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC-app.proto",
}
