version: '3'
services:

  client:
    build:
      context: ./
      dockerfile: client/Dockerfile
    image: client
    container_name: client
    restart: always
    ports:
      - 50050:50050

  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    image: server
    container_name: server
    restart: always
    ports:
      - 50051:50051

